language: php

sudo: false

matrix:
  include:
    - php: '5.6'
      env: WP_VERSION=master WP_MULTISITE=0
    - php: '5.2'
      env: WP_VERSION=master WP_MULTISITE=1
    - php: '5.6'
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: '5.5'
      env: WP_VERSION=master WP_MULTISITE=0
    - php: '5.5'
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: '5.4'
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: '5.4'
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: '5.5'
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: '5.5'
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: '5.3'
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: '5.4'
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: 'hhvm'
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 'hhvm'
      env: WP_VERSION=4.1 WP_MULTISITE=1

before_script:
- phpenv local 5.6
- phpenv local --unset
- PLUGIN_SLUG=$(basename $(pwd))
- export WP_DEVELOP_DIR=/tmp/wordpress/
- git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
- cd ..
- cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
- cd /tmp/wordpress/
- cp wp-tests-config-sample.php wp-tests-config.php
- sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
- sed -i "s/yourusernamehere/travis/" wp-tests-config.php
- sed -i "s/yourpasswordhere//" wp-tests-config.php
- mysql -e "CREATE DATABASE wordpress_tests;" -uroot
- cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
- phpenv rehash

script:
- cd tests
- ./test.sh
